### ISSUE TITLE
RadSideDrawer style isn't changed if app is launched.

### ISSUE THREAD

**Issue by valera1401** [NathanaelA/nativescript-themes#10]
After changing theme of the running app, RadSideDrawer  stays in the previous style.

**Comment by NathanaelA** [comment]
@valera1401 - is this RSD a root element or an element of a page?

**Comment by valera1401** [comment]
@NathanaelA RSD is a root element like in this demo app
https://github.com/telerik/nativescript-ui-samples-angular/blob/master/sidedrawer/app/navigation/app.component.html

**Comment by NathanaelA** [comment]
Thanks -- probably a bug in RSD; sometimes I can work around them...   Not sure the time line for a fix; since all open source work is totally unpaid work; it always has the lowest priority..

**Comment by valera1401** [comment]
@NathanaelA  Thank you for your responses.
Please notice that if a theme is applied inside of, for example, app.component constructor, everything works fine.

**Comment by bundyo** [comment]
The problem is that frame.topmost() now gets the last frame that navigated and there is no frame around RSD too. I'll add a PR for this.
