### ISSUE TITLE
Theme not getting applied in Nativescript Angular Project

### ISSUE THREAD

**Issue by sivaprasad-kiranum** [NathanaelA/nativescript-themes#13]
When the Nativescript Angular project has defined component level css files, the theme file set with the call to `Themes.applyTheme('yellow-theme.css');` is not working.

The call to `Themes.applyTheme('yellow-theme.css');` is working only when all the classes are defined in `app.css` and nothing defined in the component level css files.

**Comment by microsoftlibrary** [comment]
It's the same as my case.

**Comment by microsoftlibrary** [comment]
I use nodejs12,angular8,nativescript6.

**Comment by sivaprasad-kiranum** [comment]
@NathanaelA Can you please provide an update?

**Comment by NathanaelA** [comment]
To my knowledge the maintained ProPlugins version 
   https://npm.proplugins.org/-/web/detail/@proplugins/nativescript-themes
works on Angular.
