### ISSUE TITLE
Adding {N} 3.0 support

### ISSUE THREAD

**Issue by SandipFichadiya** [NathanaelA/nativescript-themes#3]
Hello, thanks for great plugin :) I upgraded to {N} 3.0 & this plugin is broken.

As far as I can see, the methods & properties like `parseCss()` & `appSelectors` are removed from `application` in 3.0. I couldn't find any alternative methods to this.

Do you have any plans to update this plugin soon or may be have an idea what to change? because I need to release an app & I need to decide whether to stick with 2.5 for now or I can upgrade to 3.0.

**Comment by NathanaelA** [comment]
I'm not sure the time table for upgrading to v3.0 yet.   Pretty much any plugin that deals with UI and/or properties is broken in v3.0.0...

**Comment by ozexpert** [comment]
what's the major reason that it's not supported in v3.0.0? i've also tried,, giving me an error message saying 

```
CONSOLE ERROR [native code]: ERROR TypeError: undefined is not an object (evaluating 'curSelectors.length')
CONSOLE ERROR [native code]: ERROR CONTEXT [object Object]
```

**Comment by NathanaelA** [comment]
@ozexpert - The reason is that there was a lot of internal redesign of a lot of classes in 3.0.0.   It had MAJOR breaking changes.    ANY plugins that tie in deep, use properties, or are UI based will fail to run on 3.0 w/o changes being done to them...

**Comment by alexziskind1** [comment]
Hi. Is this PR going to be merged? There are some dependence on this plugin in a demo app I'm working on.
Thanks

**Comment by NathanaelA** [comment]
@alexziskind1 - This isn't a PR.   This requires development effort to track down why it isn't working.  It is on my TODO list...

**Comment by erjdriver** [comment]
Any update on when this plugin with be NS 3.x compatible?

**Comment by bgildson** [comment]
Analyzing the changes in NS, I found the following to apply another theme...
```javascript
require('application').setCssFileName('my-other-theme.css');
const frame = require('ui/frame').topmost();
if (frame && frame.currentPage)
  frame.currentPage._refreshCss();
```

**Comment by erjdriver** [comment]
_refreshCss() is not callable from a Page instance.

No idea how you're compiling the above code.

**Comment by bgildson** [comment]
if you are using with TypeScript replace
```typescript
frame.currentPage._refreshCss();
```
by
```typescript
(<any>frame.currentPage)._refreshCss();
```

**Comment by erjdriver** [comment]
Genius!

Thank you that worked.

**Comment by erjdriver** [comment]
For NS 3.3 - replace _refreshCss() with _onCssStateChange()

**Comment by batistafrancis** [comment]
[ERROR TypeError: Cannot read property 'length' of undefined](https://github.com/NathanaelA/nativescript-themes/issues/4)

**Comment by NathanaelA** [comment]
Please note I have finally had a chance to trace everything down -- however an issue in NS 4.x is stopping me from being able to support it properly at this point 
https://github.com/NativeScript/NativeScript/issues/5911 
https://github.com/NativeScript/NativeScript/issues/5912 

Please bug them on that issue if you want this fixed.  :grinning:    

I can make the plugin so it replaces the app.css and that would work; but the original plugin left all your declared CSS alone; including your application wide css and just allowed you to dynamically swap just the "theme" css w/o messing anything up...   So at this point I hope they will fix one of the two issues.

The above `setCssFileName` that was put as a possible recommendation just replaces your standard `app.css` file...

**Comment by NathanaelA** [comment]
Please note the current version does support NS 5 and later
