### ISSUE TITLE
Is this project working again?

### ISSUE THREAD

**Issue by waynerobinson** [NathanaelA/nativescript-themes#7]
I notice that the PR you submitted to NS has been accepted, does this mean this plugin works again without further modification?

**Comment by NathanaelA** [comment]
I need to re-release it with the changes; the current version on NPM doesn't have the new support.

**Comment by waynerobinson** [comment]
No problem. Thanks for you work on this. 👍

**Comment by felixgabler** [comment]
What is the current status?

**Comment by ChopShoey** [comment]
It looks like the related NativeScript issues were fixed, but this hasn't moved since November. Any updates?

**Comment by joseandrespr** [comment]
@NathanaelA thanks for your work on this, any update would be greatly appreciated.

**Comment by NathanaelA** [comment]
Yes, I just published v2.0, which has the fixes to work with NS 5.
